/**
 * @file       hcsr04.h
 * @copyright  Copyright (C) 2026 Hong Quoc Bao. All rights reserved.
 * @license    Proprietary. For educational purposes only.
 * @version    1.0.0
 * @date       2026-01-28
 * @author     Hong Quoc Bao (baoquocbao2004@gmail.com)
 *             
 * @brief      Driver for the HC-SR04 ultrasonic sensor on STM32 platforms.
 *             Provides functions to initialize the sensor and read the
 *             distance in centimeters.
 *
 * @note       This driver relies on one hardware timer for echo pulse
 *             measurement and one EXTI pin for echo detection.
 *             The timer should be configured with a 1MHz clock frequency (1 tick = 1µs).  
 * 
 * @example
 * // --- How to use this driver ---
 * // 1. In main(), after peripheral initialization:
 * HCSR04_Init(&htim1); // e.g., using TIM1
 *
 * // 2. In the main application loop:
 * float distance = HCSR04_Read();
 * if (distance > 0) {
 *   // Process the valid distance
 * }
 *
 * // 3. Forward the EXTI interrupt callback from main.c:
 * void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
 *   if (GPIO_Pin == ECHO_Pin) {
 *     HCSR04_EXTI_Callback();
 *   }
 * }
 */

/* Define to prevent recursive inclusion ------------------------------ */
#ifndef INC_HCSR04_H_
#define INC_HCSR04_H_

/* Includes ----------------------------------------------------------- */
#include "main.h"

/* Public defines ----------------------------------------------------- */
/* Public enumerate/structure ----------------------------------------- */
/* Public macros ------------------------------------------------------ */
/* Public variables --------------------------------------------------- */

/* Public function prototypes ----------------------------------------- */

/**
 * @brief Initializes the HC-SR04 driver.
 * @details This function stores the handle of the timer used for echo pulse
 *          measurement and starts the timer in base mode. This function must be
 *          called once before any other function in this driver.
 *
 * @param[in]     htim  Pointer to a TIM_HandleTypeDef structure that contains
 *                      the configuration information for the specified timer.
 *                      The timer should be configured to have a 1MHz clock
 *                      frequency (1 tick = 1 microsecond).
 *
 * @attention The timer provided must already be initialized by the corresponding
 *            MX_TIMx_Init() function generated by CubeMX.
 *
 * @return None.
 */
void HCSR04_Init(TIM_HandleTypeDef *htim);

/**
 * @brief Reads the distance from the HC-SR04 sensor.
 * @details This function triggers the sensor, waits for the echo pulse to be
 *          captured by the EXTI interrupt, and then calculates the distance
 *          in centimeters. This is a blocking function with a timeout of 50ms.
 *
 * @param None.
 *
 * @return
 *  - Distance in centimeters (float, > 0).
 *  - -1.0f: If a timeout occurred (e.g., object is too far or sensor is disconnected).
 */
float HCSR04_Read(void);

/**
 * @brief Interrupt handler for the sensor's echo pin.
 * @details This function should be called from the main EXTI callback
 *          (HAL_GPIO_EXTI_Callback) whenever an interrupt is detected on
 *          the echo pin. It captures the start and end times of the echo pulse.
 *          This is not meant to be called directly by the user application.
 *
 * @param None.
 *
 * @attention This function must be placed inside `HAL_GPIO_EXTI_Callback` in
 *            `main.c` or `stm32fxxx_it.c` and be guarded by a check for the
 *            correct GPIO pin.
 *
 * @return None.
 */
void HCSR04_EXTI_Callback(void);

#endif // INC_HCSR04_H_

/* End of file -------------------------------------------------------- */
